docs/backends/github.rst
docs/configuration/settings.rst

- Capitalise GitHub consistently
- Change App Id and Secret to reflect GitHub's naming
- Use gender-neutral language when talking about people

Update GitHub documentation

---

docs/configuration/django.rst

Instructions are broken when using South / Django 1.6 as South will try to use the default 'migrations' directory and fail.
This tells South to use the alternate directory.

Update Django instructions to fix South migrations

---

social/backends/yahoo.py
social/tests/backends/test_yahoo.py

The sorting method to get the primary email email is reversed. 
Note the default behavior of python sorting on a Boolean arrays is to putting False first. for example.
>>> a=[True,False]
>>> a.sort()
>>> a
[False, True]

YahooOAuth failed to get primary email if multiple email found in the profile.

---

social/backends/spotify.py

Spotify's `access_token` expires after a few hours. To be able to refresh the token, we need to be storing `refresh_token`.

Store Spotify's refresh_token.

---

social/backends/jawbone.py

I've found out that jawbone authentication throws an exception  on "auth_complete" and fixed it.

Jawbone authentification fix

---

social/backends/open_id.py

If a user chooses not to share their email via the OpenId login page,
we end up passing through None as the 'email' value, which ends up
raising a "column 'email' cannot be null" error on some databases.
Blank string is fine.

Ensure email is not None

---

requirements-python3.txt
requirements.txt
setup.py
social/backends/open_id.py
social/tests/backends/open_id.py
social/tests/requirements-python3.txt
social/tests/requirements.txt

- Using PyJWT 0.4.1 (or newer)
- Relying on PyJWT to verify ID token audience and issuer
Replaces #486.

Updated PyJWT Dependency

---

docs/backends/google.rst

Add the deprecation warning for OAuth 1.0 according: https://developers.google.com/accounts/docs/OAuth
Update Google+ Sign-In documentation completing more information and applying the latest changes. Source:
https://developers.google.com/+/web/signin/

Fix Google documentation

---

social/backends/slack.py

An update to the previously submitted slack integration. If the scope is reduced to `identity` only, we have less data available. This new code properly handles both a scope of `identity` only, as well as the default scope of `identity,read`

Slack improvements

---

examples/pyramid_example/example/__init__.py
examples/pyramid_example/example/auth.py
examples/pyramid_example/example/models.py

* include template engine
* remove duplicated line
* fix parameter
* fix session

Fix example of pyramid

---

social/storage/sqlalchemy_orm.py

base64.encodestring() returns "bytes" type, this fails type check with sqlalchemy (pypostgresql driver for sqlalchemy here) with python3.
Calling .decode() converts the result to "str" type, and database insert/update works.
This patch also works with python2 (converting from "str" to "unicode").

fix python3 handling of openid backend on sqlalchemy storage

---

docs/pipeline.rst
docs/use_cases.rst

This is for two reasons:
a) Using the verb "import" suggests that the module/function should be
imported which is not true; we want a "dotted path notation" string
rather than a reference to the method.
b) "import" is an invalid module name anyway, so as an example of dotted
path notation it is faulty. (Okay, it might actually be possible using
`types` and `sys.modules` but.. yeah)
Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>

Don't use "import" in example method paths docs to avoid confusion

---

social/backends/reddit.py

Currently, the Reddit username is used to generate a username when creating a new user, but for existing users it doesn't get stored in the database. This fix adds the username to `extra_data`, aliasing the Reddit attribute `name` to the `extra_data` attribute `username`, thus letting you more reliably know your users' Reddit usernames.

Include username in Reddit extra_data

---

docs/backends/qiita.rst
social/backends/qiita.py
social/tests/backends/test_qiita.py

Qiita(https://qiita.com) is a famous SNS for engineers in Japan. 
Please feel free to merge it.

add qiita backend

---

social/backends/facebook.py

https://developers.facebook.com/docs/graph-api/securing-requests
Graph API calls from a server can be better secured by adding a
parameter called appsecret_proof.
The app secret proof is a sha256 hash of your access token, using the
app secret as the key.
$appsecret_proof= hash_hmac('sha256', $access_token, $app_secret)
the result as an appsecret_proof parameter must be added to each call
you make from server.
Securing with appsecret_proof is optional (but enabled by default for
new Facebook apps) so add appsecret_proof param is contoled by
SOCIAL_AUTH_FACEBOOK_APPSECRET_PROOF = True|False
Default is True

[facebook-oauth2] Verifying Graph API Calls with appsecret_proof

---

docs/backends/google.rst

I didn't find information about how to get the email address, so I investigated and added it to the doc.

Add extra info on Google+ Sign-In doc

---

examples/django_example/example/settings.py
social/backends/kakao.py

Fix Issue : #538 
and also, added KakaoOAuth2 on example app.

fix issue #538 : disable redirect_state on KakaoOAuth2

---

social/backends/weibo.py

This is a fix to avoid error when user access_token auth in weibo backend. Please review it

Fix Issue #532

---

docs/backends/eveonline.rst
examples/cherrypy_example/local_settings.py.template
examples/django_example/example/settings.py
examples/django_me_example/example/settings.py
examples/flask_example/settings.py
examples/flask_me_example/settings.py
examples/pyramid_example/example/settings.py
examples/tornado_example/settings.py
examples/webpy_example/app.py
social/backends/eveonline.py

I have added a simple OAuth2 backend for the MMO "EVE Online".
https://developers.eveonline.com/resource/single-sign-on
http://www.eveonline.com/
Tested with the Django default example.

Add backend for EVE Online Single Sign-On (OAuth2)

---

requirements-python3.txt
requirements.txt
setup.py
social/backends/exacttarget.py
social/backends/open_id.py
social/tests/backends/open_id.py
social/tests/requirements-python3.txt
social/tests/requirements.txt

Yesterday we released PyJWT [v1.0.0](https://github.com/jpadilla/pyjwt/releases/tag/1.0.0) which fixes some reported security vulnerabilities. Although this project doesn't seem to be affected, it would still be good idea to require PyJWT>=1.0.0,<2.0.0 instead.

Require PyJWT>=1.0.0,<2.0.0

---

social/apps/django_app/default/migrations/0002_add_related_name.py

The Django app is missing a migration due to Django 1.7 treating *any* changes to the model as migrations.
Ref #516

Add missing migration for Django app

---

social/backends/vend.py

New backend for http://www.vendhq.com/ 
At this point they're user profile is experimental so getting user parameters isn't included, simply getting the access token for subsequent api calls.

Added support for Vend

---

social/backends/strava.py

Currently you can't disconnect strava from the site. This sets the deauthorize url and sets approriate data for revoking token on strava site.

Add revoke token ability to strava

---

social/apps/django_app/__init__.py
social/apps/django_app/default/config.py
social/strategies/django_strategy.py

Added some initialization code to a new ready method in the PythonSocialAuthConfig because of changes in Django.  See https://docs.djangoproject.com/en/1.7/ref/applications/ and https://docs.djangoproject.com/en/1.7/releases/1.7/.
I'm a big fan and feel free to disregard if you already got some code in the works.
Thank you!

update for django 1.9

---

social/actions.py

- Allow inactive users to login, this is controlled by the
`SOCIAL_AUTH_INACTIVE_USER_LOGIN` setting.
I want to be able to allow inactive users to be logged in.  I have written a middleware that redirects these users to a reactivation page that currently requires the user to be logged in to work. 
I modified the `social.actions.do_complete` method so it would login inactive users depending on the setting `SOCIAL_AUTH_INACTIVE_USER_LOGIN`, which defaults to `False`.

Allow inactive users to login

---

social/apps/django_app/utils.py

This commit https://github.com/omab/python-social-auth/commit/f57e0caf4ec06f3b9a2367d9ff3897e2a3a71608 made trailing slashes optional.
The side effect of that is that the redirect_uri is created without a trailing slash.
With this change the standard Django APPEND_SLASH is checked when generating the redirect url.

Append trailing slash in Django

---

social/apps/django_app/default/migrations/0003_alter_email_max_length.py

Django 1.8 starts to set max length of EmailField to 254.

Alter email max length for Django app

---

social/pipeline/user.py

After call clean function, the final_username maybe empty and  `storage.user.user_exists(username=final_username)` will return `False`, then the loop would be skipped.  
Finally, the username would be the unclean name.

Fix the final_username may be empty and will skip the loop.

---

social/backends/fitbit.py

According to
https://wiki.fitbit.com/display/API/OAuth+1.0a+Authentication#OAuth1.0aAuthentication-Notes,
the base url for the oauth authroization page is
https://www.fitbit.com, not https://api.fitbit.com. Soon they will
redirect authorize requests to [api](api.fitbit.com) to [www](www.fitbit.com),
which will increase page load time for end users

fix Fitbit OAuth 1 authorization URL

---

social/pipeline/user.py

@omab 
Fix in this PR is changing `current_value` checking to allow to change empty and protected user fields.
Issue described in [ISSUE#671](https://github.com/omab/python-social-auth/issues/671).
Plz review this PR.
Thanks.

PR fix `user_details` pipeline issue

---

MANIFEST.in

Fixes #623, all tests pass in tox.

Keep the egg-info directory in the sdist

---

social/backends/bitbucket.py
social/tests/backends/test_bitbucket.py

Bitbucket has had a v2.0 version of their REST API out for some time. This PR updates the Bitbucket backend to use the v2.0 REST API for user and e-mail resources.
In addition, this PR follows the [Bitbucket API documentation guidance](https://confluence.atlassian.com/display/BITBUCKET/Use+the+Bitbucket+REST+APIs#UsetheBitbucketRESTAPIs-uuid-mainUniversallyUniqueIdentifier(UUID)) that user UUIDs should be used as account identifiers instead of the username since usernames can change.

Updated Bitbucket backends to use newer v2.0 APIs

---

Changelog

I noticed that commit 76a27b2 made some of my commit logs show up in old versions, because the commits were authored some time ago. None of the SAML commits were present in any releases before 0.2.11. This PR fixes the changelog so that nobody will be confused :)

Fix wrong placement of changelog commits in 76a27b2

---

docs/backends/saml.rst
social/backends/saml.py
social/tests/requirements.txt

The SAML backend can now use the latest official release of python-saml, rather than a fork, since the release now includes the required changes. Version 2.1.3 is largely the same as the commit hash previously specified, with one notable difference being that the "NameIDFormats" setting change that I had proposed was rejected in favor of [a simpler fix](https://github.com/onelogin/python-saml/commit/3a5847be93fd7e3af695d791989825cc6c118808) that should meet the same goals.
So, this PR:
* Uses the official release of python-saml instead of the fork
* Removes the now-unsupported `NameIDFormats` setting, which was unlikely to be needed by most people anyways. Those who do need to override the `NameIDFormat` can configure it using the `SOCIAL_AUTH_SAML_SP_EXTRA` dict, but that is unlikely to …

Use official python-saml 2.1.3 release, remove now-unsupported setting

---

docs/backends/bitbucket.rst
social/backends/bitbucket.py
social/backends/oauth.py
social/tests/backends/test_bitbucket.py

Bitbucket launched OAuth2 support a few weeks back. This PR adds an OAuth2 backend to python-social-auth and updates the documentation accordingly.
This PR is inclusive of #652. The diff will probably be a little bit clearer once it is merged in.

Added an OAuth2 backend for Bitbucket

---

.gitignore
docs/backends/github_enterprise.rst
social/backends/github.py
social/backends/github_enterprise.py
social/tests/backends/test_github_enterprise.py

I just extended the Github module, so the functions used for Github Enterprise are exactly the same as the Github ones.
I've tested it against a trial version of Github Enterprise I have running and it works fine.
The tests work fine too as it's an identical copy of the Github v3 API.
Added docs as well.
Had to add `DEFAULT_SCOPE = ['read:org']` as it couldn't figure out organisation membership on Github Enterprise (normal Github works just fine without it - as long as you publicise your membership)

added support for Github Enterprise

---

docs/configuration/settings.rst

The behavior change documented in https://github.com/omab/python-social-auth/issues/276 may not be what users expect, especially those migrating from django social auth. This PR better documents the new user redirect behavior.

Improve docs on SOCIAL_AUTH_NEW_USER_REDIRECT_URL

---

social/backends/goclioeu.py

Add support for goclio's european servers. goclio.eu is pratically the same as goclio.com, but it has a different app registry, so you have different (key, secret) pairs for each domain and different domains on the API calls.

support for goclio.eu service

---

social/apps/django_app/default/models.py

Django 1.8 increases default max_length of EmailField from 75 to 254. Since max_length is not currently specified, but the initial migration contains the 1.8 default of 254, Django 1.7 will think there's a migration to create, decreasing the max_length to 75. This can be fixed by explicitly setting the max_length to 254.

Close #622 by explicitly setting email length (compatibility with Django 1.7)

---

social/backends/linkedin.py

Right now when you use .content, the token is bytes, not text, and so you run into an error when saving it to the session. Similar error in issue #139.

text -> content solves "is not JSON serializable"

---

README.rst
docs/backends/index.rst
docs/backends/uber.rst
social/backends/uber.py
social/tests/backends/test_uber.py

- Backend UberOAuth2 added
- Tests for UberOAuth2 backend added
- Docs for backend added
- References to backend docs added in intro.rst and backends/index.rst

Add support for Uber OAuth2 - Uber API v1

---

social/apps/django_app/default/managers.py
social/apps/django_app/default/models.py

The details of this PR are laid out in #698.  The two things this PR does:
1. Create an abstract class for the django ``UserSocialAuth`` model so it can be extended
1. Adds an object manager to the ``UserSocialAuth`` class which is the "django way" of performing actions that the class method ``get_social_auth(cls, provider, uid)`` is trying to do.  (``UserSocialAuth.get_social_auth(...)`` should now be deprecated in favor of ``UserSocialAuth.objects.get_social_auth(...)``)
Fixes #698

Make an abstract verstion of django's UserSocialAuth's model so it can be extended (fixes #698)

---

social/backends/vk.py

Sometime vk_api function returns None (when vk.com is down for example) but user_data expects dict and fails.

VK API workflow fix if error happens on vk-side

---

social/apps/tornado_app/routes.py

When reversing URLs, tornado doesn't interpret the regex optional symbol '?'. This causes the redirect_uri to be https://example.com/complete/mybackend/? with the question mark appended. Some providers will simply append to this uri, causing URLs like https://example.com/complete/mybackend/??code=.... with two question marks. This makes the interpretation of the query string fail.
The provider in this case is [django-oidc-provider](https://github.com/juanifioren/django-oidc-provider). Arguably that library should be smarter in constructing the redirection, but removing the question mark from the uri solves these kind of issues.
Alternatively we could strip the question mark from the uri in the tornado strategy in [here](https://github.com/omab/python-social-auth/blob/470a597f7d5dbb189b72e2 …

Fix redirect_uri issue with tornado reversed url

---

social/storage/sqlalchemy_orm.py

SQLAlchemy can't detect changes to the extra_data property of a user. By wrapping in a MutableDict it can and will save updated data (like bearer tokens in case of OAuth).

Save extra_data on login

---

social/backends/facebook.py

Addresses Issue #670. The problem was that unicode strings are default in Python 3, but the base64 and hmac libraries require byte strings. The fix was to explicitly encode and decode the strings as necessary. I tested this patch in Python 2.7.6 and 3.4.0.

Python 3 support for facebook-app backend

---

social/storage/base.py

Some backends (e.g. OpenIdConnect) have an `id_token` next to an `access_token` and `refresh_token`, so they all need to be stored.

Store all tokens when tokens are refreshed

---

social/backends/shopify.py

To use Shopify's `Redirection URL` settings, redirect state should not be appended.

Add REDIRECT_STATE = False

---

docs/pipeline.rst
docs/use_cases.rst

Tuple in pipeline's documentation should be ended with coma

---

social/backends/instagram.py

On last week instagram has changed the authorization routes from 'https://instagram.com/oauth/authorize' to 'https://api.instagram.com/oauth/authorize', and this have break all systems with old route. This change isn't well documented by instagram, but on documentation there is examples with new urls.
https://www.instagram.com/developer/authentication/

Changed instagram backend to new authorization routes

---

social/backends/vk.py

Fix get_user_id method for modern VK API response (5.34 tested) where no uid param - fallback to get_user_id from BaseAuth class which gets uid by self.ID_KEY

Fix vk backend

---

docs/configuration/django.rst
docs/configuration/index.rst
docs/configuration/settings.rst
docs/index.rst
docs/logging_out.rst
docs/pipeline.rst
docs/strategies.rst
docs/use_cases.rst

This PR includes mostly grammar fixes, but does include one substantive change the a command in Django docs: running `./manage.py migrate` is all that's required to sync the database.

Fixes a few grammar issues in the docs

---

social/backends/saml.py

This fix allows the SAML Backend to support Python 2.6

Formatter fixes for SAML to support Py2.6

---

social/apps/django_app/urls.py

In django_app/urls.py:
* Use a list instead of `patterns`
* Use view callables instead of strings
Fixes #804, #754

Fix Django 1.10 deprecation warnings

---

social/backends/weibo.py

While running `python manage.py makemessages` in a Django project, it complains that the `weibo.py` file is not using a known encoding. Replacing `utf8` with `utf-8` removes the warning.
````
xgettext: ./lib/python2.7/site-packages/social/backends/weibo.py:1: Unknown encoding "utf8". Proceeding with ASCII instead.
````

Fix xgettext warning due to unknown encoding

---

docs/backends/github_enterprise.rst

The documentation for the Github Enterprise backend lacked an explanation on how to set the API URL for the Github Enterprise appliance. This PR fixes that.

add github enterprise docs on how to specify the API URL

---

docs/backends/odnoklassnikiru.rst
social/backends/odnoklassniki.py

Hi, there.
About a year ago odnoklassniki social network switched out their domain and name to ok.
You can chech it by url (http://ok.ru/group/57170323832868/topic/62946583920676). 
I've updated documentation and oauth entry points.

[Fix] update odnoklasniki docs to new domain ok

---

social/backends/saml.py
social/tests/backends/test_saml.py

The SAML login handler fails with a KeyError if the idp query param is not given, which leads to a 500 response. Raise AuthMissingParameter instead.

SAML: raise AuthMissingParameter if idp param missing

---

social/backends/pocket.py

There is a wrong name of the social auth key. I think, 'POCKET_CONSUMER_KEY' shoud be a 'SOCIAL_AUTH_POCKET_KEY'. 'POCKET_CONSUMER_KEY' makes a ''400 Client Error".

modifed wrong key names in pocket.py

---

social/backends/oauth.py

`BaseOAuth2.do_auth` wasn't storing the access token to be passed to the pipeline. As a result, backends inheriting from `BaseOAuth2` wasn't storing the token because `OAuthAuth.extra_data` never had the token information passed to it.
Reference: 
`BaseOAuth1.do_auth`
https://github.com/omab/python-social-auth/blob/master/social/backends/oauth.py#L185-L193
`OAuthAuth.extra_data`
https://github.com/omab/python-social-auth/blob/master/social/backends/oauth.py#L39-L46
Related:
https://github.com/omab/python-social-auth/issues/416

BaseOAuth2: Store access token in response if it does not exist

---

README.rst
docs/backends/index.rst
docs/backends/ngpvan_actionid.rst
docs/intro.rst
social/backends/ngpvan.py
social/tests/backends/test_ngpvan.py
social/tests/models.py

Put together a full implementation of the NGPVAN [ActionID](http://developers.ngpvan.com/action-id) OpenID backend.
They'll offer OpenID Connect soon, but supporting their version of OpenID connect could involve some significant refactoring of the OpenID Connect implementation already in `python-social-auth`, so starting out with the standard OpenID 1.1 implementation would probably be a good first step.
Let me know what you think.
Thanks!

Added support for NGPVAN ActionID OpenID

---

social/apps/django_app/default/migrations/0001_initial.py
social/apps/django_app/default/migrations/0003_alter_email_max_length.py
social/apps/django_app/default/models.py
social/pipeline/user.py

After spending too much time debugging why my extra entry in `SOCIAL_AUTH_USER_FIELDS` was `None`, if figured out that the issue lies in `social.pipeline.create_user`. If the extra field in `SOCIAL_AUTH_USER_FIELDS` is a boolean evaluated to `False`, and it´s provided in kwargs, it will return `None` instead of the correct `False` value.
```Python
>>> kwargs = {'field': False}
>>> details = {}
>>> results = kwargs.get('field') or details.get('field')
>>> print(results)
None
>>> results = kwargs.get('field', details.get('field'))
>>> print(results)
False
```

Fix wrong evaluation of boolean kwargs

---

social/apps/django_app/default/fields.py

Removed metaclass syntax to break the dependency on django.db.models.SubfieldBase, which has been deprecated in Django 1.9 and will be removed with Django 1.10.
Fixes #804 and #754. Extends fix provided by #806.

Fix Django 1.10 Deprecation Warning "SubfieldBase has been deprecated."

---

social/backends/evernote.py
social/backends/weixin.py
social/exceptions.py
social/tests/backends/test_evernote.py
social/tests/backends/test_facebook.py
social/utils.py

When oauth provider responds with error, we only got `AuthCanceled` exception.
It is hard to understand, why provider refuses to accept our request. We can't easily log the response.
This patch saves response in attribute of  `AuthCanceled` exception (if it is possible).
And users of library can log the response to understand, what really happened.

Pass response to AuthCancel exception

---

social/apps/django_app/default/fields.py

Without this extra_data field can be returned as its raw serialized string...

django 1.8+ compat to ensure to_python is always called when accessing result from db..

---

social/apps/django_app/default/fields.py
social/apps/django_app/default/migrations/0004_auto_20160423_0400.py

The default should be an empty dict, not a string value.
Fixes #898

Corrected default value of JSONField

---

social/backends/open_id.py
social/tests/backends/open_id.py

- Added support for passing kwargs to jwt.decode()
- Updated iat claim validation
The first commit adds support for passing kwargs to `jwt.decode()`, allowing for great flexibility to determine, for example, which signing algorithms are used or the expected value of the audience claim.
The second commit (a) instructs PyJWT to verify the iat claim and ensure a value is present, and (b) makes the value against which the claim is compared configurable. I don't know why I hardcoded this to 10 minutes; but, that is not in the spec, and should be configurable for each individual client.

Updates to OpenIdConnectAuth

---

social/backends/oauth.py

This value is useful for authentication servers (AS) that may provide multiple types of tokens. Most servers use the `Bearer` token type; however, we at @edx are transitioning to using `JWT`. The ability to make the switch without having to change our backend would be ideal. Storing the token type means we can avoid hardcoding the value and let the access token response determine which scheme is used for future requests made using the issued token.

Storing token_type in extra_data field when using OAuth 2.0

---

social/actions.py

The three possible sources of **redirect-uri** to `backend.strategy.redirect()` call would most likely supply a relative uri. From my encounter with this, the **redirect-uri** got loaded over http which caused Mixed-content error since the social platform disconnection request was made over https scheme.
So passing any of the relative **redirect-uri** to `backend.strategy.absolute_uri()` would pass the absolute **redirect-uri** with the desired scheme to `backend.strategy.redirect()`.

Fix mixed-content error of loading http over https scheme after disconnection from social account

---

docs/use_cases.rst

Link is broken and points to a SPAM/Scam website. Looked for a replacement link but it appears the author no longer has a blog, I checked his twitter and googled him and the article. Fixes issue #860

Removed broken link in use cases docs fixing #860

---

social/backends/coursera.py

currently `coursera` backend is designed to use custom `username` key as `ID_KEY`
the `username` value is prepared and stored in `details` dict by `get_user_details`, however it doesn't override `get_user_id` method, which results in the app trying to fetch `username` from `response` dict.

fixes empty uid in coursera backend

---

social/apps/django_app/default/migrations/0002_add_related_name.py
social/storage/django_orm.py

We use stock `auth.User` model for administrators (without social auth) and custom `UserAccount` model for other types of users with enabled social auth. So we have `SOCIAL_AUTH_USER_MODEL = 'customauth.UserAccount'`.
The patch fixes the following failure:
```
./manage.py migrate --fake-initial
django.db.utils.IntegrityError: insert or update on table "social_auth_usersocialauth" violates foreign key constraint "social_auth_usersocialauth_user_id_17d28448_fk_auth_user_id"
DETAIL:  Key (user_id)=(225873) is not present in table "auth_user".
```

django migration should respect SOCIAL_AUTH_USER_MODEL setting

---

README.rst
docs/backends/line.rst
social/backends/line.py

Line (https://line.me/en/) messenger OAuth2 support.

Line support added

---

social/strategies/base.py

BaseStrategy.validate_email() will check if a Code object exists, but not that the Code object's email field matches the email parameter passed to the method; indeed, the email parameter isn't used at all.
In a nutshell: if you have the social.pipeline.mail.mail_validation backend set up with SOCIAL_AUTH_PASSWORDLESS, you can gain access to any user account on the system. Log in once to get a genuine verification code, take note of the URL callback to the 'social:complete' view (e.g. /social/complete/email/?verification_code=b855c8966abf45e6aaac89af9b12f7c8&email=attacker%40gmail.com ), then hit the same URL but with a different email (e.g. /social/complete/email/?verification_code=b855c8966abf45e6aaac89af9b12f7c8&email=admin%40site.com).

VULNERABILITY - BaseStrategy.validate_email() doesn't actually check email address

---

social/apps/django_app/default/config.py
social/apps/django_app/default/migrations/0002_add_related_name.py
social/apps/django_app/default/migrations/0003_alter_email_max_length.py

now displays social_auth instead of 'default' when running migration tool

Add Django AppConfig Label of "social_auth" for migrations

---

social/apps/pyramid_app/models.py
social/storage/sqlalchemy_orm.py

Fix for https://github.com/omab/python-social-auth/issues/945 to make it work with Flask/SQLAlchemy again, reverts some of the changes in https://github.com/omab/python-social-auth/commit/a52ee69cc641018bbf32c6fd599a6c30036b3086

Fix for flask/SQLAlchemy: commit on save (but not when using Pyramid)

---

examples/flask_example/__init__.py
examples/flask_example/models/user.py
examples/flask_example/routes/main.py
examples/flask_me_example/__init__.py
examples/flask_me_example/models/user.py
examples/flask_me_example/routes/main.py
social/apps/flask_app/routes.py

Importing flask.ext.login is deprecated, use flask_login instead.
See pallets/flask#1135 for details.

Switch from flask.ext.login to flask_login

---

social/apps/django_app/default/migrations/0004_auto_20160423_0400.py

This appears to have been broken since it was introduced by #908.

Corrected migration dependency

---

social/apps/django_app/default/admin.py

See https://docs.djangoproject.com/en/1.9/releases/1.8/#selected-methods-in-django-db-models-options-options
and
https://docs.djangoproject.com/en/1.9/ref/models/meta/#migrating-old-meta-api

Removed dep method get_all_field_names method from Django 1.8+

---

social/storage/django_orm.py

We have an API client that sends a ton of requests in parallel after getting a token from a different oauth service.  As a result, we have a race condition for local account creation. This patch handles that by seeing if there was IntegrityError as an indication that another fork created the user already and then trying to find the created user to return instead of making it.

Added exception handling for user creation race condition in Django

---

social/actions.py
social/tests/test_utils.py
social/utils.py

So imagine your auth server lives on a subdomain. How are you going to use ?next= parameter if you want user to get back to the main domain, or even some other domain for whatever reason?
This solves it by introducint the ALLOWED_REDIRECT_HOSTS setting. Disadvantage of this approach is that you can't possibly apply it to a wildcard.
Another approach could be to figure out the lowest level common domain, but it just feels less safe.
Don't hesitate to criticize this, as I just chose the most obvious solution. There might be a better way to achieve what I want.

Multiple hosts in redirect sanitaion.

---

docs/backends/yammer.rst

In 2015, Yammer revised their security requirements to require the exact redirect_uri, rather than just the domain.  As a result, it is important that python-social-auth specify the appropriate redirect_uri in the documentation.
The documentation format in this PR matches the format of other backends, such as [foursquare](https://github.com/omab/python-social-auth/blob/master/docs/backends/foursquare.rst)
[yammer documentation](https://developer.yammer.com/blog/action-required-please-make-this-simple-update-prior-to-august-25-2015)

Add redirect_uri to yammer docs

---

docs/backends/battlenet.rst
social/backends/battlenet.py

Currently the Battlenet oauth backend only returns battletags and no longer returns the Account ID which is needed to hit other endpoints. This change makes the function return more than just the battletag.
Would love for some other opinions on this, just getting started with Battlenet api stuff today, may be misunderstanding something.
Also updated docs with what it took to get the backend working for me.

Revise battlenet endpoint to return account ID and battletag

---

docs/backends/twitter.rst
social/backends/twitter.py
social/tests/backends/test_twitter.py

Added support for optional `include_email` parameter for Twitter backend.
Added test for checking email address receiving.
Updated docs.
Corresponding issue: #825

Added optional 'include_email' query param for Twitter backend.

---

docs/pipeline.rst

Improved pipeline file introducing some minor changes.

Rewrited pipeline.rst

---

social/apps/django_app/default/migrations/0001_initial.py
social/apps/django_app/default/migrations/0002_add_related_name.py
social/apps/django_app/default/migrations/0003_alter_email_max_length.py
social/apps/django_app/default/migrations/0004_auto_20160423_0400.py

The app rename in #916 breaks migrations for previously-setup systems. This commit informs Django that the migrations under the new app name replace the migrations under the old app name.
Fixes #991

Fixed Django Migrations

---

README.rst

Please only use dashes as separator if the date format is ISO 8601 (YYYY-MM-DD)

fix date in deprecation notice title
