omab/python-social-auth

- docs/backends/slack.rst
- social/backends/slack.py
Support for Slack https://api.slack.com/docs/oauth
> Slack backend

- social/apps/django_app/default/migrations/0001_initial.py
> Fixed extra_data field in django 1.7 initial migration

- social/apps/django_app/default/migrations/0001_initial.py
- social/apps/django_app/default/models.py
Updated for #490, if necessary.
> Added nonce unique constraint

- README.rst
- docs/backends/coursera.rst
- examples/django_example/example/settings.py
- social/backends/coursera.py
- social/tests/backends/test_coursera.py
This is an implementation of Coursera OAuth2-based backend. There is no option to refresh access token though.
> Coursera backend

- README.rst
- docs/backends/launchpad.rst
- social/backends/launchpad.py
Add support for Launchpad OpenId
> Add support for Launchpad OpenId

- social/backends/mendeley.py
Pull request for issue #501 .
Updated mendeley oauth2 to use new api resource and also updated to grab new profile_id, name and bio.
> Pull Request for #501

- social/strategies/django_strategy.py
This is a fix to avoid errors in Django 1.7. Please review it.
> Fix: Issue #508

- docs/backends/dribbble.rst
- social/backends/dribbble.py
- social/tests/backends/test_dribbble.py
Dribble(https://dribbble.com/) is a famous SNS for designer. 
Please feel free to merge it.
> Add dribbble backend.

- social/strategies/django_strategy.py
I am not using MergeDict because it will be deprecated. Thank you @kosmos342
> Fixed issue: GET dictionary is immutable.

- site/index.html
> Typo in index.html

- docs/backends/index.rst
- docs/backends/wunderlist.rst
- docs/intro.rst
- examples/cherrypy_example/local_settings.py.template
- examples/django_example/example/settings.py
- examples/django_me_example/example/settings.py
- examples/flask_example/settings.py
- examples/flask_me_example/settings.py
- examples/pyramid_example/example/settings.py
- examples/tornado_example/settings.py
- examples/webpy_example/app.py
- social/backends/wunderlist.py
- social/tests/backends/test_wunderlist.py
This PR adds [wunderlist](https://www.wunderlist.com/) oauth2 backend.
> Wunderlist oauth2 backend

- README.rst
> Add wunderlist backend to the list

- requirements-python3.txt
- requirements.txt
- setup.py
> Increase min request-oauthlib version to 0.3.1

- social/backends/base.py
- social/pipeline/social_auth.py
> Start pipeline with default details arg

- social/backends/live.py
> set redirect_state to false for live oauth2

- Makefile
- setup.cfg
This will require to additionally install `wheel` and `twine` locally.
> Build a wheel, and upload with twine

- docs/backends/changetip.rst
- social/backends/changetip.py
Support for Login with ChangeTip, including docs.
https://www.changetip.com/api
> ChangeTip Backend

- README.rst
Simple documentation only patch.
> Just add Moves App to the list of providers on README 

- social/backends/weixin.py
Weixin is Tencent's icq, in China there are million's people use it.
> add weixin backends

- social/backends/clef.py
- social/tests/backends/test_clef.py
It looks like somehow the the Clef backend diverged from the the Clef API. This PR adds a fix for that divergence.
Thank you for all of your hard work maintaining this library :)
> Fix Clef backend

- docs/backends/meetup.rst
- social/backends/meetup.py
To close: https://github.com/omab/python-social-auth/issues/677
> Meetup.com OAuth2 provider

- social/backends/echosign.py
OAuth2 backend for echosing api:
https://secure.echosign.com/public/docs/restapi/v3#!/
> echosign OAuth2 backend

- docs/backends/orbi.rst
- social/backends/orbi.py
- social/tests/backends/test_orbi.py
Turn it up~!.
Thx great library XD.
> Add orbi backend

- examples/flask_me_example/routes/main.py
fix use of login_required decorator; doesn't work if wrapping a func already wrapped with app.route
> flask_me_example fix

- social/strategies/pyramid_strategy.py
Ability to apply Pyramid Authentication Policies #321
> Support Pyramid Authentication Policies

- docs/backends/justgiving.rst
- social/backends/justgiving.py
justgiving.com is one of the UK's largest charity fundraising platforms. They are quickly expanding their API and will shortly be releasing their OAuth integration that i've already been using with the python-social-auth app.
> Added justgiving.com OAuth2 backend

- social/backends/odnoklassniki.py
Fix scope separator which is ";" in OK api
Fix logic of get_user_details, it will correctly process email in OK response (because OK may return email in response in case you have permissions for that and scope "GET_EMAIL")
> Fix odnoklassniki backend

- docs/backends/qq.rst
- social/backends/qq.py
sometimes nickname will duplicate with another qq account, this PR can fix it
> use qq openid as username

- docs/backends/naver.rst
- social/backends/naver.py
- social/tests/backends/test_naver.py
naver.com is the largest and most popular search engine in Republic of Korea.
- Backend NaverOAuth2 added
- Docs for NaverOAuth2 added
- Tests for NaverOAuth2 backend added
> Add naver.com OAuth2 backend

- social/utils.py
But instead use the standard recommended getLogger function https://docs.python.org/2/library/logging.html#logger-objects
> Do not instantiate Logger directly

- social/backends/amazon.py
- social/backends/twilio.py
* amazon backend: change authorization URL from http to https
* twilio backend: fix backend name in comment
> Minor backend fixes

- README.rst
- docs/backends/index.rst
- docs/backends/pinterest.rst
- docs/intro.rst
- social/backends/pinterest.py
- social/tests/backends/test_pinterest.py
Add pinterest oauth2 backend.
Details: https://developers.pinterest.com/docs/api/authentication/
./run_tox.sh
...
py26: commands succeeded
py27: commands succeeded
py33: commands succeeded
py34: commands succeeded
pypy: commands succeeded
doc: commands succeeded
congratulations :)
> Add pinterest backend

- social/backends/azuread.py
Microsoft has changed the OAuth2 endpoints so this PR updates those. Microsoft has also added a couple of params to the refresh token request, so we have also added them.
> Azure AD updates

- social/apps/pyramid_app/models.py
Support all kind of data type (like uuid) of User.id on Pyramid
> Support all kind of data type (like uuid) of User.id on Pyramid

- README.rst
- docs/backends/fitbit.rst
- docs/intro.rst
- examples/cherrypy_example/local_settings.py.template
- examples/django_example/example/settings.py
- examples/django_me_example/example/settings.py
- examples/flask_example/settings.py
- examples/flask_me_example/settings.py
- examples/pyramid_example/example/settings.py
- examples/tornado_example/settings.py
- examples/webpy_example/app.py
- social/backends/fitbit.py
- social/tests/backends/test_fitbit.py
This adds OAuth 2.0 support to Fitbit.
Closes #733
> Fitbit OAuth 2.0 support

- README.rst
- docs/backends/index.rst
- docs/backends/sketchfab.rst
- examples/django_example/example/settings.py
- examples/django_me_example/example/settings.py
- social/apps/django_app/tests.py
- social/backends/sketchfab.py
- social/tests/backends/test_sketchfab.py
As documented here:
https://sketchfab.com/developers/oauth
> Add Sketchfab OAuth2 backend

- social/backends/weixin.py
Weixin have two oauth method:
1. User login with web, when user scan 2D barcode；
2. User click green submit button in Weixin app.
These two way are very different in development scene.
Beacause my poorly english and developer who use weixin oauth
almost are Chinese.I'll explain in Chinese.
微信有两种授权方式:
1. 通过微信开放平台注册的账号，用户可以在web上点击用微信登陆，此时微信
会生成二维码，用户扫描后即可登陆；
2. 通过微信app登陆，开发者在微信开放平台注册微信公众号(服务号)后，用户
打开需要授权的页面后会先出现一个有绿色确认按钮的页面，当用户点击登陆后
完成登陆逻辑.
注意
1. 如果你是在两个平台注册的账号，用户体系需要用微信的uninionid自己
做唯一性关联，因为微信认为这是两个app即使你用同一个开放者账号注册；所以
现象是同一个用户用微信打开两个不同场景的服务登陆时，openid是不同的，但是
可以通过uninionid来关联,唯一确认用户。
2. 微信app的登陆方式请添加一个可以按照日期或者其他任何随机变化的参数，
因为微信对于转发有奇怪的限制，当转发量到一定程度后，微信会废弃这个链接，
现象是你自己在朋友圈可以看到自己转发的链接，但是你的朋友们却看不到。
> Add weixin public number oauth backend.

- README.rst
- docs/backends/index.rst
- docs/backends/untappd.rst
- social/backends/untappd.py
This is my first contribution, so please let me know if there are any stylistic or other changes that you'd like me to make.  Thanks!
ref: https://untappd.com/api/docs
> Add support for Untappd as an OAuth v2 backend

- social/backends/coding.py
add coding(https://coding.net) oauth2
> add coding oauth

- social/pipeline/user.py
When using postgres the username field can be a varchar with no maximum size.
> username max_length can be None

- social/backends/facebook.py
- social/tests/backends/test_facebook.py
> Update facebook api version to v2.7

- social/apps/pyramid_app/views.py
Not sure if this is the best approach. Please let me know if it's any good.
> Allow POST requests for auth method so OpenID forms could use it that way

- docs/backends/index.rst
- docs/backends/upwork.rst
- docs/intro.rst
- examples/cherrypy_example/local_settings.py.template
- examples/django_example/example/settings.py
- examples/django_me_example/example/settings.py
- examples/flask_example/settings.py
- examples/flask_me_example/settings.py
- examples/pyramid_example/example/settings.py
- examples/tornado_example/settings.py
- examples/webpy_example/app.py
- social/backends/upwork.py
- social/tests/backends/test_upwork.py
> ADDED: upwork backend

- social/strategies/pyramid_strategy.py
Didn't spend much time investigating, but basic case works, at least on Pyramid 1.7.
> "else" scenario in Pyramid html func was causing an exception every time.

- social/apps/django_app/default/fields.py
This commit 10a6f5570a4471d156c2bc06ecd4313189d23172 broke compatible with Django < 1.8, fixed
> Fixed Django < 1.8 broken compatibility

- social/apps/django_app/middleware.py
> Subclass MiddlewareMixin for Django 1.10 compat

- MIGRATING_TO_SOCIAL.md
Going to update this as I upgrade my project.
> Update migration guide for Django

- social/backends/facebook.py
in social_core.backends.facebook only classes FacebookOAuth and FacebookAppOAuth2 are refined
> in social_core.backends.facebook only classes FacebookOAuth
